apiVersion: v1
kind: Service
metadata:
  name: tconfigd
  namespace: tratteria-system
spec:
  type: ClusterIP
  ports:
    - name: rules
      port: 9060
      targetPort: 9060
      protocol: TCP
    - name: webhook
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: tconfigd
